---
# The Fedora 29 image we are using
# (geerlingguy/docker-fedora29-ansible:latest) needs a cache update
# and all packages updated; otherwise, we get sporadic errors from dnf
# about "No such file or directory: /var/lib/dnf/rpmdb_lock.pid".
- name: Group hosts by OS distribution and major version
  hosts: all
  tasks:
    - name: Group hosts by OS distribution and major version
      group_by:
        key: os_{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}
- name: Update all packages (Fedora 29)
  hosts: os_Fedora_29
  tasks:
    - name: Update all packages (Fedora 29)
      dnf:
        name: "*"
        state: latest
        update_cache: yes
